# Generated by Django 4.1.7 on 2023-03-21 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leagueName', models.CharField(max_length=100, unique=True)),
                ('yearOfFoundation', models.SmallIntegerField()),
                ('domesticCup', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FootballTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=100, unique=True)),
                ('yearOfFoundation', models.SmallIntegerField()),
                ('ground', models.CharField(max_length=50)),
                ('presidentName', models.CharField(max_length=100)),
                ('league', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='footballTeamsApp.footballleague')),
            ],
        ),
    ]
