# Generated by Django 4.1.7 on 2023-03-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballTeamsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballleague',
            name='confederation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='footballleague',
            name='numberOfTeams',
            field=models.SmallIntegerField(null=True),
        ),
    ]
