# Generated by Django 4.1.7 on 2023-03-21 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footballTeamsApp', '0002_footballleague_confederation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.SmallIntegerField()),
                ('height', models.SmallIntegerField()),
                ('weight', models.SmallIntegerField()),
                ('team', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='footballTeamsApp.footballteam')),
            ],
        ),
    ]
